<!DOCTYPE html>
<html>
  <head>
    <title>Random Words</title>
    <link rel="stylesheet" href="/static/css/blueprint/screen.css" type="text/css" media="screen, projection"/>
    <link rel="stylesheet" href="/static/css/blueprint/print.css" type="text/css" media="print"/> 
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="/static/css/blueprint/ie.css" type="text/css" media="screen, projection"/>
    <![endif]-->
    <link rel="stylesheet" href="/static/css/base.css" type="text/css" media="screen, projection"/> 
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans+Mono" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Quattrocento+Sans" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.min.js"></script>
    <script type="text/javascript" src="/static/js/root.js"></script>
  </head>
  <body>

    <div class="container">

      <h1 class="prepend-top center">Random Words</h1>

      <div class="blurb">
        These words were generated by analyzing the occurance frequency of letter combinations in a sample document.
        Using the resulting statistics, words can be generated through a simple 
        <a href="http://en.wikipedia.org/wiki/Markov_chain" target="_blank">Markov</a> walk.  The goal is to generate words
        which which hopefully appear similar (and pronouncable) to other words in the English language.
      </div>

      <div class="center prepend-top">
        <div class="span-3">
          <br/>
        </div>

        <form id="settings" method="get" action="/words">

          <div class="left-align span-6">
            <fieldset>
              <legend>Strength</legend>
            
              <label for="alternate_case">
                <input type="checkbox" name="alternate_case" value="Y"/>
                Alternate Case
              </label>
              <br/>

              <label for="add_number">
                <input type="checkbox" name="add_number" value="Y"/>
                Add Number
              </label>
              <br/>

              <label for="add_punctuation">
                <input type="checkbox" name="add_punctuation" value="Y"/>
                Add Punctuation
              </label>
            </fieldset>
          </div>
          <div class="left-align span-6 col-border">           
            <fieldset>
              <legend>Options</legend>
              <label for="number">Number of Words to Generate: </label><br/>
              <select name="number">
                %for i in range(1, 6):
                <option 
                   value="${50 * i }"
                   
                   %if i== 2:
                   selected="selected"
                   %endif

                   >
                  ${50 * i}
                </option>
                %endfor
              </select>
              <br/>

              <label for="min_length">
                Word Length: 
              </label><br/>

              <select name="min_length">
                %for i in range(2, 13):
                <option 
                   value="${i}"

                   %if i == 6:
                   selected="selected"
                   %endif

                   >${i}</option>

                %endfor
              </select>                

              to

              <select name="max_length">
                %for i in range(2, 13):
                <option 
                   value="${i}"

                   %if i == 10:
                   selected="selected"
                   %endif

                   >${i}</option>

                %endfor
              </select>                

              characters
              
            </fieldset>           
          </div>
        </form>
        
        <div class="span-6 last">
          <fieldset>
            <legend>Generate</legend>
            <div class="center clear prepend-top">
              <label for="automatically_refresh">
                <input type="checkbox" name="automatically_refresh"
                       value="Y" checked="checked"
                       id="auto-refresh"/>
                Automatically Refresh
              </label><br/>

              <button id="refresh-now" type="button" disabled="disabled">
                Refresh Now
              </button><br/>
              <span id="paused" style="display:none"><em>Paused</em></span><br/>
            </div>

          </fieldset>
        </div>

      </div>

      <hr class="space">

      <div class="center clear">
        <a id="url" href=""></a>
      </div>
      
      <div id="words-container" class="prepend-top">
        %for i in range(1, 7):
        <div class="words span-4 ${'last' if i == 6 else ''}"></div>
        %endfor

        <br class="clear"/>
      </div>

    </div>
  </body>
</html>
