<!DOCTYPE html>
<html>
  <head>
    <title>Random Words</title>
    <link rel="stylesheet" href="/static/css/blueprint/screen.css" type="text/css" media="screen, projection"/>
    <link rel="stylesheet" href="/static/css/blueprint/print.css" type="text/css" media="print"/> 
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="/static/css/blueprint/ie.css" type="text/css" media="screen, projection"/>
    <![endif]-->
    <link rel="stylesheet" href="/static/css/base.css" type="text/css" media="screen, projection"/> 
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans+Mono" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Quattrocento+Sans" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.min.js"></script>
    <script type="text/javascript" src="/static/js/root.js"></script>
  </head>
  <body>

    <div class="container">

      <h1>Random Words</h1>

      <div class="blurb">
        These words were generated by analyzing the occurance frequency of letter combinations in a sample document.
        Using the resulting statistics, words can be generated through a simple 
        <a href="http://en.wikipedia.org/wiki/Markov_chain" target="_blank">Markov</a> walk.  The goal is to generate words
        which which hopefully appear similar (and pronouncable) to other words in the English language.
      </div>

      <div class="center">
        <form id="settings" method="get" action="/words">
          <label for="alternate_case">
            <input type="checkbox" name="alternate_case" value="Y"/>
            Alternate Case
          </label>

          <label for="add_number">
            <input type="checkbox" name="add_number" value="Y"/>
            Add Number
          </label>

          <label for="add_punctuation">
            <input type="checkbox" name="add_punctuation" value="Y"/>
            Add Punctuation
          </label>

        </form>
      </div>

      <hr class="space"/>

      <div class="words span-6"></div>
      <div class="words span-6"></div>
      <div class="words span-6"></div>
      <div class="words span-6 last"></div>

    </div>
  </body>
</html>
